language: c

compiler:
  - gcc

before_script:
  - (git clone https://github.com/maximilianvoss/clogger.git && cd clogger && cmake -G "Unix Makefiles" && make && sudo make install)

script:
  - cmake -G "Unix Makefiles" && make